name: Debug

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Echo github
        run: |
          echo "github.action_path: ${{ github.action_path }}"
          echo "github.action_ref: ${{ github.action_ref }}"
          echo "github.action_repository: ${{ github.action_repository }}"
          echo "github.actor: ${{ github.actor }}"
          echo "github.event: ${{ github.event }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event_path: ${{ github.event_path }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.path: ${{ github.path }}"
          echo "github.repository_owner: ${{ github.repository_owner }}"
